'use client';

import { useState, useEffect } from 'react';
import { fluidSizing } from '@/lib/fluidSizing';
import { slugify } from '@/lib/utils/slugify';
import { api } from '@/lib/api-client';
import { alerts } from '@/shared/alertSystem';
import Button from '../atoms/Button';

interface ProjectSlugFieldProps {
  title: string;
  existingSlug?: string;
  onManualModeChange?: (isManualMode: boolean) => void;
  onSlugUpdated?: (newSlug: string) => void;
}

export default function ProjectSlugField({
  title,
  existingSlug,
  onManualModeChange,
  onSlugUpdated,
}: ProjectSlugFieldProps) {
  const [originalSlug, setOriginalSlug] = useState<string>('');
  const [previewSlug, setPreviewSlug] = useState<string>('');
  const [slugValidation, setSlugValidation] = useState<{ valid: boolean; warning?: string }>({ valid: true });
  const [isManualMode, setIsManualMode] = useState(false);
  const [manualSlug, setManualSlug] = useState<string>('');
  const [isSavingSlug, setIsSavingSlug] = useState(false);
  const [hasManualSlug, setHasManualSlug] = useState(false);
  const [isInitialized, setIsInitialized] = useState(false);

  // Inicializar con el slug existente en modo edición (solo una vez)
  useEffect(() => {
    if (existingSlug && !isInitialized) {
      setOriginalSlug(existingSlug);
      setPreviewSlug(existingSlug);
      
      // Detectar si el slug existente es manual (diferente al que se generaría automáticamente)
      if (title) {
        const autoGeneratedSlug = slugify(title);
        if (existingSlug !== autoGeneratedSlug) {
          // El slug es diferente al que se generaría automáticamente = es manual
          setHasManualSlug(true);
        }
      }
      
      setIsInitialized(true);
    }
  }, [existingSlug, title, isInitialized]);

  // Validar slug
  const validateSlugPreview = (slug: string): { valid: boolean; warning?: string } => {
    if (!slug || slug.length === 0) {
      return {
        valid: false,
        warning: 'El título debe contener al menos un carácter alfanumérico',
      };
    }

    if (slug.length > 100) {
      return {
        valid: false,
        warning: `El slug es muy largo (${slug.length}/100 caracteres)`,
      };
    }

    if (!/^[a-z0-9-]+$/.test(slug)) {
      return {
        valid: false,
        warning: 'El slug contiene caracteres no permitidos',
      };
    }

    if (/^-|-$/.test(slug)) {
      return {
        valid: false,
        warning: 'El slug no puede empezar o terminar con guión',
      };
    }

    return { valid: true };
  };

  // Generar preview del slug cuando cambia el título (solo si no está en modo manual Y no hay slug manual guardado)
  // IMPORTANTE: Solo ejecutar después de la inicialización para evitar sobrescribir slugs manuales
  useEffect(() => {
    if (isInitialized && !isManualMode && !hasManualSlug) {
      if (title) {
        const newSlug = slugify(title);
        setPreviewSlug(newSlug);
        setSlugValidation(validateSlugPreview(newSlug));
      } else {
        setPreviewSlug('');
        setSlugValidation({ valid: true });
      }
    }
  }, [title, isManualMode, hasManualSlug, isInitialized]);

  // Notificar al padre cuando cambia el modo manual
  useEffect(() => {
    if (onManualModeChange) {
      onManualModeChange(isManualMode);
    }
  }, [isManualMode, onManualModeChange]);

  const handleToggleManualMode = () => {
    if (!isManualMode) {
      setManualSlug(previewSlug || originalSlug);
    }
    setIsManualMode(!isManualMode);
  };

  const handleManualSlugChange = (value: string) => {
    setManualSlug(value);
    setSlugValidation(validateSlugPreview(value));
  };

  const handleSaveManualSlug = async () => {
    if (!existingSlug) {
      alerts.error('Error', 'Solo puedes editar la URL manualmente en proyectos existentes');
      return;
    }

    if (!slugValidation.valid) {
      alerts.error('Error', slugValidation.warning || 'El slug no es válido');
      return;
    }

    try {
      setIsSavingSlug(true);
      const response = await api.regenerateProjectSlug(originalSlug, '', manualSlug);
      
      if (response.success && response.data) {
        const { newSlug, changed, oldSlug } = response.data as any;
        
        if (changed) {
          setOriginalSlug(newSlug);
          setPreviewSlug(newSlug);
          setIsManualMode(false);
          setHasManualSlug(true);
          alerts.success(
            'URL Actualizada',
            `La URL se actualizó de "${oldSlug}" a "${newSlug}"`
          );
          
          if (onSlugUpdated) {
            onSlugUpdated(newSlug);
          }
        } else {
          alerts.info('Sin Cambios', 'La URL ya está actualizada');
          setIsManualMode(false);
          setHasManualSlug(true);
        }
      } else {
        alerts.error('Error', response.error?.message || 'No se pudo actualizar la URL');
      }
    } catch (error) {
      alerts.error('Error', 'Ocurrió un error al actualizar la URL');
    } finally {
      setIsSavingSlug(false);
    }
  };

  const handleUnlockSlug = async () => {
    if (!existingSlug || !title) {
      alerts.error('Error', 'No se puede desbloquear la URL');
      return;
    }

    try {
      setIsSavingSlug(true);
      
      // Generar slug automático desde el título actual
      const autoSlug = slugify(title);
      
      // Actualizar en la base de datos usando el endpoint de regeneración
      const response = await api.regenerateProjectSlug(originalSlug, title, '');
      
      if (response.success && response.data) {
        const { newSlug, changed } = response.data as any;
        
        setOriginalSlug(newSlug);
        setPreviewSlug(newSlug);
        setHasManualSlug(false);
        
        if (changed) {
          alerts.success(
            'URL Desbloqueada',
            `La URL se regeneró automáticamente a "${newSlug}"`
          );
        } else {
          alerts.info(
            'URL Desbloqueada',
            'La URL se regenerará automáticamente al cambiar el título'
          );
        }
        
        if (onSlugUpdated) {
          onSlugUpdated(newSlug);
        }
      } else {
        alerts.error('Error', response.error?.message || 'No se pudo desbloquear la URL');
      }
    } catch (error) {
      alerts.error('Error', 'Ocurrió un error al desbloquear la URL');
    } finally {
      setIsSavingSlug(false);
    }
  };

  if (!previewSlug && !isManualMode) {
    return null;
  }

  return (
    <div className="mt-2 space-y-2">
      {isManualMode ? (
        // Modo manual: input editable
        <div className={`p-3 rounded-lg ${
          !slugValidation.valid 
            ? 'bg-red-500/10 border border-red-500/30' 
            : 'bg-admin-dark-elevated/50 border border-admin-primary/10'
        }`}>
          <div className="flex items-center gap-2 mb-2">
            <span className="text-text-muted font-mono text-xs">URL Manual:</span>
            <span className="text-yellow-400 text-xs">⚠ Modo edición manual</span>
          </div>
          <div className="flex items-center gap-2">
            <span className="text-text-muted text-sm">/projects/</span>
            <input
              type="text"
              value={manualSlug}
              onChange={(e) => handleManualSlugChange(e.target.value)}
              className="flex-1 bg-admin-dark-surface border border-admin-primary/30 rounded px-3 py-1.5 text-text-primary font-mono text-sm focus:outline-none focus:border-admin-primary focus:ring-2 focus:ring-admin-primary/20"
              placeholder="mi-url-personalizada"
            />
            <Button
              type="button"
              onClick={handleSaveManualSlug}
              variant="primary"
              size="sm"
              icon="check"
              disabled={!slugValidation.valid || isSavingSlug}
              isLoading={isSavingSlug}
            >
              Guardar URL
            </Button>
            <Button
              type="button"
              onClick={handleToggleManualMode}
              variant="secondary"
              size="sm"
              icon="x"
              disabled={isSavingSlug}
            >
              Cancelar
            </Button>
          </div>
          {!slugValidation.valid && slugValidation.warning && (
            <div className="mt-2 text-red-400 text-xs flex items-center gap-1">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
              </svg>
              {slugValidation.warning}
            </div>
          )}
        </div>
      ) : (
        // Modo automático: preview
        <div className={`p-3 rounded-lg ${
          !slugValidation.valid 
            ? 'bg-red-500/10 border border-red-500/30' 
            : hasManualSlug
              ? 'bg-green-500/10 border border-green-500/30'
              : 'bg-admin-dark-elevated/50 border border-admin-primary/10'
        }`}>
          <div className="flex items-center gap-2 text-xs">
            <span className="text-text-muted font-mono">URL:</span>
            <code className={`font-mono flex-1 ${
              !slugValidation.valid ? 'text-red-400' : hasManualSlug ? 'text-green-400' : 'text-admin-primary'
            }`}>
              /projects/{previewSlug}
            </code>
            {hasManualSlug && (
              <span className="text-green-400 text-xs flex items-center gap-1">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clipRule="evenodd" />
                </svg>
                URL manual fija
              </span>
            )}
            {!slugValidation.valid && slugValidation.warning && (
              <span className="text-red-400 text-xs flex items-center gap-1">
                <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 20 20">
                  <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7 4a1 1 0 11-2 0 1 1 0 012 0zm-1-9a1 1 0 00-1 1v4a1 1 0 102 0V6a1 1 0 00-1-1z" clipRule="evenodd" />
                </svg>
                {slugValidation.warning}
              </span>
            )}
            {slugValidation.valid && !hasManualSlug && originalSlug && originalSlug !== previewSlug && (
              <span className="text-yellow-400 text-xs">
                ⚠ Cambió desde: {originalSlug}
              </span>
            )}
          </div>
        </div>
      )}
      
      {/* Botón para activar modo manual o desbloquear URL */}
      {!isManualMode && existingSlug && (
        <div className="flex items-center gap-3">
          <button
            type="button"
            onClick={handleToggleManualMode}
            className="text-text-muted hover:text-admin-primary text-xs flex items-center gap-1 transition-colors"
          >
            <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15.232 5.232l3.536 3.536m-2.036-5.036a2.5 2.5 0 113.536 3.536L6.5 21.036H3v-3.572L16.732 3.732z" />
            </svg>
            {hasManualSlug ? 'Cambiar URL manual' : 'Insertar URL manual'}
          </button>
          {hasManualSlug && (
            <button
              type="button"
              onClick={handleUnlockSlug}
              disabled={isSavingSlug}
              className={`text-yellow-400 hover:text-yellow-300 text-xs flex items-center gap-1 transition-colors ${
                isSavingSlug ? 'opacity-50 cursor-not-allowed' : ''
              }`}
            >
              {isSavingSlug ? (
                <>
                  <span className="inline-block animate-spin rounded-full border-t-2 border-b-2 border-yellow-400 w-3 h-3"></span>
                  Desbloqueando...
                </>
              ) : (
                <>
                  <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 11V7a4 4 0 118 0m-4 8v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2z" />
                  </svg>
                  Desbloquear URL (volver a automático)
                </>
              )}
            </button>
          )}
        </div>
      )}
    </div>
  );
}
